<footer class="w3-container dark w3-margin-4">
    <table class="w3-table">
        <tbody>
            <tr>
                <td width=400>
                    <a target="_self" href="http://www.vrstevnice.com">
                        <img src="../odkazy1/ja05.jpg" width="75" height="100" alt="logo"/></a>
                    <a target="_self" href="http://www.vrstevnice.com">
                        na hlavní stránku</a>
                </td>
                <td valign=bottom width=400>
                    <font size=2>copyright </font>
                    <font size=4>&copy;</font>
                    <font size=2>
                    <a href="../kontakt/kontakt.htm">vrstevnice</a>
                    2016</font>
                </td>
            </tr>
        </tbody></table>
</div></body>
</footer>
