
<div class="w3-topnav w3-xlarge w3-margin-4 dark">
    <img src="odkazy2/ikonky.jpg">
    <a target="_blank"  href="indexbak.html"><i class="fa fa-home "></i></a>
    <a href="akce/2016/akce2016.html" >
        &gt;akce 2016</a>

    <a target="_blank" href="akce/bylo_rozcestnik.html">
        &gt;co bylo</a>

    <a target="_blank" href="kontakt/kontakt.html">
        &gt;kontakt</a>

    <a target="_blank" href="ja.html">
        &gt;já...</a>

    <a target="_blank" href="mojekolo/mojekolo.html">
        &gt;moje kolo...</a> 

    <a target="_blank" href="blog/blog.html">
        &gt;můj blog...</a>    

    <a target="_blank" href="template/template.html">
        &gt;template</a>
</div>
