
<div class="w3-topnav w3-xlarge w3-margin-4 dark">
    <img src="odkazy2/ikonky.jpg">
    <a target="_blank"  href="indexbak.html"><i class="fa fa-home "></i></a>
    <a href="http://vrstevnice.com/akce/2016/akce2016.html" >
        &gt;akce 2016</a>

    <a target="_blank" href="http://vrstevnice.com/akce/bylo_rozcestnik.htm">
        &gt;co bylo</a>

    <a target="_blank" href="http://vrstevnice.com/kontakt/kontakt.htm">
        &gt;kontakt</a>

    <a target="_blank" href="ja.html">
        &gt;já...</a>

    <a target="_blank" href="http://vrstevnice.com/mojekolo/mojekolo.html">
        &gt;moje kolo...</a> 

    <a target="_blank" href="http://vrstevnice.com/blog/blog.html">
        &gt;můj blog...</a>    

    <a target="_blank" href="template.html">
        &gt;template</a>
</div>
